default: &default
  adapter: postgresql 
  encoding: utf8
  pool: 5
  host: localhost
  username: postgrails
  password: SeaL2000
  timeout: 5000

development:
  <<: *default
  database: hartl_sample_app_development 

test: &test
  <<: *default
  database: hartl_sample_app_test 

cucumber:
  <<: *test